### ISSUE TITLE
[Feat] Implement Complete Transaction Flow (Webhook URL) and Verify Transaction

### ISSUE THREAD

**Issue by eanolue** [hngprojects/hng_boilerplate_csharp_web#104]
## Description:
Implement the flow to complete a transaction after initialization. This process involves redirecting the user to the Paystack authorization URL (FE) and handling the callback (webhook) to confirm the transaction status. Create an endpoint to verify the status of a transaction using the Paystack API. This endpoint will allow our system to check the current status of a transaction at any time.

## Purpose:
To finalize the payment process by redirecting the user to Paystack's secure payment page and handling the webhook event to update our system with the transaction result.

## Expected Outcome:
A seamless flow where users can complete their payments, and our system accurately records the transaction status.

## Requirements:
1. Implement a redirect mechanism to Paystack's authorization URL.
2. Create a callback endpoint to receive transaction status updates (webhook event) from Paystack.
3. Update transaction status in the database.
4. Provide a Verify Endpoint to poll Paystack to confirm the transaction in case the webhook failed.
5. Integrate with Paystack's verification API.
6. Create a Transaction Table.

## DB Schema Updates:
Add the following fields to the transactions table:
- `Id` (Guid)
- `UserId` (Guid) FK
- `ProductId` (Guid) FK
- `Type` (TransactionType Enum, e.g., payment, reverse)
- `Status` (TransactionStatus Enum, e.g., Pending, Completed, Failed)
- `Partners` (TransactionIntegrationPartners Enum, e.g., Paystack, Stripe)
- `Amount` (decimal)
- `Reference` (string)
- `CreatedAt` (DateTime)
- `PaidAt` (DateTime?)
- `ModifiedAt` (DateTime?)

## Acceptance Criteria:
1. The callback endpoint correctly processes Paystack's response.
2. Transaction status is accurately updated in the database.
3. Webhook events are properly handled and processed.
4. Able to verify a transaction by calling the verify endpoint.
5. The endpoint successfully communicates with Paystack's verification API.
6. It correctly handles and validates the transaction reference.

### Callback Endpoint:
- **URL**: `/api/v1/transactions/callback`
- **Method**: `POST`
- **Authentication**: None (handled by Paystack)
- **Body Parameters**:
    - `dynamic object`: The transaction reference

#### Successful Response Body (200 OK):
```json
{
  "string": "success"
}
```

#### Error Response Body (400 Bad Request):
```json
{
  "string": "Transaction not found"
}
```

### Verify Endpoint:
- **URL**: `/api/v1/transactions/verify/:reference`
- **Method**: `GET`
- **Authentication**: Required (Bearer token)
- **Path Parameters**:
    - `reference` (string): The transaction reference to verify

#### Successful Response Body (200 OK):
```json
{
  "string": "success"
}
```

#### Error Response Body (400 Bad Request):
```json
{
  "string": "Verification Failed"
}
```

#### Error Response Body (404 Not Found):
```json
{
  "string": "Reference cannot be null!"
}
```

## Error Handling:
- Invalid or missing transaction reference
- Failed transactions
- Timeout in communication with Paystack
- Database update failures

## Security Measures:
1. Validate the integrity of Paystack's callback data.
2. Use HTTPS for all communications.
3. Implement IP whitelisting for Paystack's callback requests.
4. Use environment variables for storing sensitive data.
5. Implement proper logging, ensuring no sensitive data is logged.

## Tasks:
- [ ] Implement the verify transaction endpoint
- [ ] Implement the callback endpoint
- [ ] Integrate with Paystack's verification API
- [ ] Implement input validation for the transaction reference
- [ ] Create error handling and logging mechanisms
- [ ] Implement authentication and authorization checks
- [ ] Write unit and integration tests
- [ ] Update API documentation
- [ ] Perform security review
