### ISSUE TITLE
[Feat]: Create Endpoint For Working With Email Templates in The System

### ISSUE THREAD

**Issue by Ace2489** [hngprojects/hng_boilerplate_csharp_web#168]
## Description
Implement a flexible and efficient system for storing, retrieving, and managing email templates on the backend. The system should focus on scalability, performance, and ease of use.

## Objectives
- Create a versatile email template storage system
- Implement efficient retrieval mechanisms
- Ensure template flexibility with placeholder support
- Provide a clean API for frontend integration

## Tasks
- [x] Design template storage architecture
  - [x] Define template structure (including placeholders)
  - [x] Determine storage method

- [x] Implement template storage
  - [x] Create data model for email templates
  - [x] Implement database storage provider

- [x] Develop template retrieval system
  - [x] Create service for async template retrieval

- [x] Design and implement API
  - [x] Create endpoints for template CRUD operations
  - [x] Develop DTO for template data transfer

- [x] Implement placeholder management
  - [x] Develop system for defining and managing placeholders
  - [ ] Create mechanism for validating placeholder usage

- [ ] Develop comprehensive test suite
  - [ ] Create unit tests for core components
  - [ ] Implement integration tests for end-to-end workflows
  - [ ] Develop performance tests for template retrieval

## Acceptance Criteria
1. Email templates can be stored and retrieved efficiently
2. Templates include flexible placeholder system
3. API provides clean, RESTful endpoints for template management
4. Placeholder validation ensures template integrity
5. Comprehensive test suite validates system reliability and performance

## API RESPONSES
GET /api/templates/{id}
### Success Response
```json
   {
   "id": "string",
  "name": "string",
  "subject": "Welcome to Our Service, {{UserName}}!",
  "bodyTemplate": "<h1>Hello {{UserName}},</h1><p>Welcome to our service! We're excited to have you on board.</p><p>Your account was created on {{SignUpDate}}.</p><p>Best regards,<br>The {{CompanyName}} Team</p>",
  "placeholders": {
    "UserName": "",
    "SignUpDate": "",
    "CompanyName": "Amazing Corp"
  }
}
```
