### ISSUE TITLE
[Feat] Implement Endpoint to Update User Language

### ISSUE THREAD

**Issue by dorisjenny27** [hngprojects/hng_boilerplate_csharp_web#230]
## Description

This issue involves creating an endpoint to update the language preference for a specific user in the system.

## Endpoint

**Method:** PUT  
**URL:** /api/v1/users/{userId}/language

## Request Body

**Content-Type:** application/json  
**Body:**
```json
{
  "language_code": "string"
}
```

## Success Response

**Status Code:** 200  
**Body:**
```json
{
  "status_code": 200,
  "message": "User language updated successfully"
}
```

## Error Responses

**Error Response (Unauthorized)**  
**Status Code:** 401  
**Body:**
```json
{
  "status_code": 401,
  "message": "Unauthorized"
}
```

**Error Response (Forbidden)**  
**Status Code:** 403  
**Body:**
```json
{
  "status_code": 403,
  "message": "Forbidden"
}
```

**Error Response (Not Found)**  
**Status Code:** 404  
**Body:**
```json
{
  "status_code": 404,
  "message": "User not found"
}
```

**Error Response (Bad Request)**  
**Status Code:** 400  
**Body:**
```json
{
  "status_code": 400,
  "message": "Invalid language code"
}
```

## Checklist

- [ ] Implement PUT /api/v1/users/{userId}/language endpoint.
- [ ] Ensure endpoint requires valid Authorization token.
- [ ] Validate the provided language code.
- [ ] Create unit tests for the endpoint.
- [ ] Update API documentation.

### Error Handling

- Invalid request parameters (400 Bad Request)
- Authentication failure (401 Unauthorized)
- Authorization failure (403 Forbidden)
- User not found (404 Not Found)
- Internal server errors (500 Internal Server Error)

## Security Measures

1. Use HTTPS for all API communications
2. Implement rate limiting to prevent abuse
3. Validate and sanitize all input parameters
4. Use environment variables for storing sensitive data
5. Implement proper authentication and authorization checks

## Tasks

1. **Create UpdateUserLanguageCommand and handler**
2. **Implement controller action for the endpoint**
3. **Implement authorization checks**
4. **Implement error handling and logging**
5. **Write unit and integration tests**
6. **Add Swagger documentation for the API endpoint**
7. **Perform security review and penetration testing**
8. **Deploy to staging environment for testing**
