### ISSUE TITLE
[Feat] Implement Endpoint to Get All Regions

### ISSUE THREAD

**Issue by dorisjenny27** [hngprojects/hng_boilerplate_csharp_web#231]
## Description

This issue involves creating an endpoint to retrieve a list of all supported regions in the system.

## Endpoint

**Method:** GET  
**URL:** /api/v1/regions

## Success Response

**Status Code:** 200  
**Body:**
```json
{
  "status_code": 200,
  "message": "Regions fetched successfully",
  "regions": [
    {
      "id": "uuid",
      "code": "string",
      "name": "string",
      "created_at": "string",
      "updated_at": "string"
    }
  ]
}
```

## Error Response

**Error Response (Unauthorized)**  
**Status Code:** 401  
**Body:**
```json
{
  "status_code": 401,
  "message": "Unauthorized"
}
```

## Checklist

- [ ] Implement GET /api/v1/regions endpoint.
- [ ] Ensure endpoint requires valid Authorization token.
- [ ] Create unit tests for the endpoint.
- [ ] Update API documentation.

### Error Handling

- Invalid request parameters (400 Bad Request)
- Authentication failure (401 Unauthorized)
- Authorization failure (403 Forbidden)
- Regions not found (404 Not Found)
- Internal server errors (500 Internal Server Error)

## Security Measures

1. Use HTTPS for all API communications
2. Implement rate limiting to prevent abuse
3. Validate and sanitize all input parameters
4. Use environment variables for storing sensitive data
5. Implement proper authentication and authorization checks

## Tasks

1. **Create GetRegionsQuery and handler**
2. **Implement controller action for the endpoint**
3. **Implement authorization checks**
4. **Implement error handling and logging**
5. **Write unit and integration tests**
6. **Add Swagger documentation for the API endpoint**
7. **Perform security review and penetration testing**
8. **Deploy to staging environment for testing**

**Comment by phoenixdahdev** [comment]
Note endpoint should be open and does not require authentication

**Comment by medusa009** [comment]
Hi, I just found out there is no Regions in the repository, please unapprove the issue.
