### ISSUE TITLE
[Feat] Implement Endpoint to Update User Region

### ISSUE THREAD

**Issue by dorisjenny27** [hngprojects/hng_boilerplate_csharp_web#232]
## Description

This issue involves creating an endpoint to update the region preference for a specific user in the system.

## Endpoint

**Method:** PUT  
**URL:** /api/v1/users/{userId}/region

## Request Body

**Content-Type:** application/json  
**Body:**
```json
{
  "region_code": "string"
}
```

## Success Response

**Status Code:** 200  
**Body:**
```json
{
  "status_code": 200,
  "message": "User region updated successfully"
}
```

## Error Responses

- **Unauthorized (401)**  
  **Body:**
  ```json
  {
    "status_code": 401,
    "message": "Unauthorized"
  }
  ```

- **Forbidden (403)**  
  **Body:**
  ```json
  {
    "status_code": 403,
    "message": "Forbidden"
  }
  ```

- **Not Found (404)**  
  **Body:**
  ```json
  {
    "status_code": 404,
    "message": "User not found"
  }
  ```

- **Bad Request (400)**  
  **Body:**
  ```json
  {
    "status_code": 400,
    "message": "Invalid region code"
  }
  ```

## Checklist

- [ ] Implement PUT /api/v1/users/{userId}/region endpoint.
- [ ] Ensure endpoint requires valid Authorization token.
- [ ] Validate the provided region code.
- [ ] Create unit tests for the endpoint.
- [ ] Update API documentation.

### Error Handling

- Invalid request parameters (400 Bad Request)
- Authentication failure (401 Unauthorized)
- Authorization failure (403 Forbidden)
- User not found (404 Not Found)
- Internal server errors (500 Internal Server Error)

## Security Measures

1. Use HTTPS for all API communications.
2. Implement rate limiting to prevent abuse.
3. Validate and sanitize all input parameters.
4. Use environment variables for storing sensitive data.
5. Implement proper authentication and authorization checks.

## Tasks

1. **Create UpdateUserRegionCommand and handler.**
2. **Implement controller action for the endpoint.**
3. **Implement authorization checks.**
4. **Implement error handling and logging.**
5. **Write unit and integration tests.**
6. **Add Swagger documentation for the API endpoint.**
7. **Perform security review and penetration testing.**
8. **Deploy to staging environment for testing.**
