### ISSUE TITLE
[Feat] Implement Create Timezone Endpoint

### ISSUE THREAD

**Issue by dorisjenny27** [hngprojects/hng_boilerplate_csharp_web#233]
## Description

This issue involves creating an endpoint to create a new timezone in the system.

## Endpoint

**Method:** POST  
**URL:** /api/v1/timezones

## Request Body

**Content-Type:** application/json  
**Body:**
```json
{
  "timezone": "America/New_York",
  "gmtOffset": "-05:00",
  "description": "Eastern Standard Time"
}
```

## Success Response

**Status Code:** 201
**Body:**
```json
{
  "id": "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p",
  "timezone": "America/New_York",
  "gmtOffset": "-05:00",
  "description": "Eastern Standard Time",
  "status_code": 201,
  "message": "Timezone created successfully"
}
```

## Error Responses

- **Conflict (409)**  
  **Body:**
  ```json
{
  "status_code": 409,
  "error": "Timezone 'America/New_York' already exists.",
  "message": "Timezone already exists"
}
  ```

- **Forbidden (403)**  
  **Body:**
  ```json
  {
    "status_code": 403,
    "message": "Forbidden"
  }
  ```

- **Bad Request (400)**  
  **Body:**
  ```json
  {
    "status_code": 400,
    "message": "Invalid timezone data"
  }
  ```

## Checklist

- [ ] Implement POST /api/v1/timezones endpoint.
- [ ] Ensure endpoint requires valid Authorization token.
- [ ] Validate the provided timezone.
- [ ] Create unit tests for the endpoint.
- [ ] Update API documentation.

### Error Handling

- Invalid request parameters (400 Bad Request)
- Timezone already exists (409 Conflict)
- Authentication failure (401 Unauthorized)
- Authorization failure (403 Forbidden)
- Internal server errors (500 Internal Server Error)

## Security Measures

1. Use HTTPS for all API communications.
2. Implement rate limiting to prevent abuse.
3. Validate and sanitize all input parameters.
4. Use environment variables for storing sensitive data.
5. Implement proper authentication and authorization checks.

## Tasks

1. **Create CreateTimezoneCommand and handler.**
2. **Implement controller action for the endpoint.**
3. **Implement authorization checks.**
4. **Implement error handling and logging.**
5. **Write unit and integration tests.**
6. **Add Swagger documentation for the API endpoint.**
7. **Perform security review and penetration testing.**
8. **Deploy to staging environment for testing.**
