### ISSUE TITLE
[Feat]Implement FAQ CRUD Functionality Using CQRS

### ISSUE THREAD

**Issue by ZEEZKING** [hngprojects/hng_boilerplate_csharp_web#239]
### Description:
- Implement the FAQ CRUD operations (Create, Read, Update, Delete) using the CQRS pattern in the application.
### Task List:

1. **Create FAQ**

- [x]   Implement CreateFaqCommand and CreateFaqCommandHandler.
- [x]  Create CreateFaqRequestDto and CreateFaqResponseDto.
- [x]   Update the FaqMappingProfile to map between CreateFaqCommand, Faq, and CreateFaqResponseDto.
- [x]   Implement POST /api/v1/faqs endpoint in FaqController.
- [x]  Write unit tests for CreateFaqCommandHandler.

2. Update FAQ

- [x]  Implement UpdateFaqCommand and UpdateFaqCommandHandler.
- [x]  Create UpdateFaqRequestDto and UpdateFaqResponseDto.
- [x]  Update the FaqMappingProfile to map between UpdateFaqCommand, Faq, and UpdateFaqResponseDto.
- [x]  Implement PATCH /api/v1/faqs/{id} endpoint in FaqController.
- [x]  Write unit tests for UpdateFaqCommandHandler.

3. Delete FAQ

- [x] Implement DeleteFaqCommand and DeleteFaqCommandHandler.
- [x]  Create DeleteFaqResponseDto.
- [x]  Update the FaqMappingProfile if necessary.
- [x]  Implement DELETE /api/v1/faqs/{id} endpoint in FaqController.
- [x] Write unit tests for DeleteFaqCommandHandler.

4. Get All FAQs

- [x]  Implement GetAllFaqsQuery and GetAllFaqsQueryHandler.
- [x]  Create FaqResponseDto and GetAllFaqsResponseDto.
- [x]  Update the FaqMappingProfile to map between Faq and FaqResponseDto.
- [x]  Implement GET /api/v1/faqs endpoint in FaqController.
 - [x] Write unit tests for GetAllFaqsQueryHandler.
### Expected Result:

- All FAQ-related endpoints should follow the CQRS pattern with consistent response formats. The functionality should be thoroughly tested with unit tests.

- Labels:
- feature
- backend
- CQRS
- FAQ

Additional Notes:
Please ensure that the response format for all CRUD operations follows the structure:

```
Success: { "Status": statusCode, "Message": "Success message", "Data": {...} }
Error: { "Status": statusCode, "Message": "Error message" }

```
