### ISSUE TITLE
[FEAT] Implement Verify Transaction Endpoint

### ISSUE THREAD

**Issue by FredChuksDev** [hngprojects/hng_boilerplate_csharp_web#83]
## Description
Create an endpoint to verify the status of a transaction using the Paystack API. This endpoint will allow our system to check the current status of a transaction at any time.

## Purpose
To provide a way to confirm the status of a transaction, especially useful for resolving discrepancies or handling cases where the callback might have failed.

## Expected Outcome
An endpoint that reliably returns the current status of a transaction by querying the Paystack API.

## Requirements
1. Integrate with Paystack's verification API
2. Handle authentication and authorization
3. Implement error handling and logging
4. Update local transaction records if necessary

## Acceptance Criteria
1. The endpoint successfully communicates with Paystack's verification API
2. It correctly handles and validates the transaction reference
3. It returns the transaction status and details in the expected format
4. It handles and returns appropriate error responses
5. The endpoint is secured with proper authentication
6. All verification attempts are logged

## Endpoint Details
```
- URL: /api/v1/transactions/verify/:reference
- Method: GET
- Authentication: Required (Bearer token)
```

## Path Parameters
- reference (string): The transaction reference to verify

### Successful Response Body (200 OK):
```json
{
  "status": true,
  "message": "Transaction verified successfully",
  "data": {
    "id": 2009945086,
    "reference": "unique_transaction_reference",
    "status": "success",
    "amount": 50000,
    "paid_at": "2023-07-23T14:00:00Z",
    "channel": "card",
    "currency": "NGN",
    "customer": {
      "id": 89929267,
      "email": "customer@example.com"
    }
  }
}
```

### Error Response Body: 400 Bad Request
```json
{
  "status": false,
  "error": "Invalid input parameters. Please check your request and try again."
}

```

### Error Response Body: 500 Internal Server Error
```json
{
  "status": 500,
  "error": "An unexpected error occurred. Please try again later or contact support."
}
```

## Error Handling
- Invalid or non-existent transaction reference
- Authentication failure
- Paystack API errors
- Internal server errors

## Security Measures
1. Use HTTPS for all API communications
2. Implement rate limiting to prevent abuse
3. Validate and sanitize the transaction reference
4. Use environment variables for storing sensitive data (e.g., Paystack secret key)
5. Implement proper authentication and authorization checks

## DB Schema Updates
No new schema updates required, but ensure the transactions table can accommodate all fields returned by Paystack's verification API.

## Tasks
- [ ] Implement the verify transaction endpoint
- [ ] Integrate with Paystack's verification API
- [ ] Implement input validation for the transaction reference
- [ ] Create error handling and logging mechanisms
- [ ] Implement authentication and authorization checks
- [ ] Write unit and integration tests
- [ ] Update API documentation
- [ ] Perform security review
- [ ] Deploy to staging environment for testing
